{% set name = "datasketch" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/datasketch-{{ version }}.tar.gz
  sha256: e42aea4c5a6f0efa0f1c8ff1183c3c52a1ac94446e8dd5892147218207cc25a4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy >=1.11
    - scipy >=1.0.0

test:
  imports:
    - datasketch
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://ekzhu.github.io/datasketch
  summary: Probabilistic data structures for processing and searching very large datasets
  dev_url: https://github.com/ekzhu/datasketch
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
