# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: datasketch
  version: "1.7.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/datasketch-${{ version }}.tar.gz
  sha256: 6e9913e923655dd5b1bc5ba6eecc1ff597b876a31720a49ed01570ea3069d9e3

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }},<4.0
    - numpy >=1.11
    - scipy >=1.0.0

tests:
  - python:
      imports:
        - datasketch
      python_version: ${{ python_min }}.*
      pip_check: true

about:
  summary: Probabilistic data structures for processing and searching very large datasets
  license: MIT
  license_file: LICENSE
  homepage: https://ekzhu.github.io/datasketch
  repository: https://github.com/ekzhu/datasketch

extra:
  recipe-maintainers:
    - rxm7706
